apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: apps
  labels:
    app: nginx
spec:
  replicas: 40
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        workload: apps
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   namespace: apps
#   labels:
#     app: nginx
# spec:
#   replicas: 20
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: 1.14.2 # 1.16.1
#           # imagePullPolicy: Never
#           ports:
#             - containerPort: 80
#       # nodeSelector:
#       #   workload: apps
#       # tolerations:
#       #   - key: "scalesetpriority"
#       #     operator: "Equal"
#       #     value: "spot"
#       #     effect: "NoSchedule"
#       # - key: "project"
#       #   operator: "Equal"
#       #   value: "system"
#       #   effect: "NoSchedule"
#       # minReadySeconds: 0
#       # strategy:
#       #   type: RollingUpdate
#       #   rollingUpdate:
#       #     maxSurge: 25
#       #     maxUnavailable: 25
